"""add_nickname_avatar_roles_permissions_to_user

Revision ID: b9d904dbc101
Revises: a6fef5e8ce78
Create Date: 2025-05-16 16:57:12.014401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d904dbc101'
down_revision: Union[str, None] = 'a6fef5e8ce78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
