"""add_nickname_avatar_roles_permissions_to_user

Revision ID: b9d904dbc101
Revises: a6fef5e8ce78
Create Date: 2025-05-16 16:57:12.014401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Assuming you might use JSONB for PostgreSQL, else remove


# revision identifiers, used by Alembic.
revision: str = 'b9d904dbc101'
down_revision: Union[str, None] = 'a6fef5e8ce78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('roles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'roles')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
