import { createApp } from 'vue'
import App from './App.vue'
import router from './router' // Vue Router
import { createPinia } from 'pinia' // Pinia

// Import Element Plus (如果需要全局注册组件或样式，但通常按需引入插件会处理)
// import ElementPlus from 'element-plus'
// import 'element-plus/dist/index.css' // Element Plus 完整样式

// Import UnoCSS entry (main.css or similar generated by UnoCSS, or directly via Vite plugin)
// Typically, UnoCSS is injected by its Vite plugin, so direct import might not be needed here.
// If you have a global stylesheet that imports UnoCSS or defines global styles:
import './styles/main.scss' // Or .css, depending on your setup

const app = createApp(App)

app.use(createPinia()) // Use Pinia
app.use(router)      // Use Vue Router
// app.use(ElementPlus) // Only if you want to register all Element Plus components globally

app.mount('#app') 